version: '3.5'
services:
  billable-hours-api-server-backend:
    restart: 'always'
    depends_on:
      - bha-mysql-docker-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 3306:3306
    volumes:
      - /data/billable-hours-api-server-backend
    container_name: billable-hours-api-server-backend
    environment:
      WAIT_HOSTS: bha-mysql-docker-container:3306
  bha-mysql-docker-container:
    image: mysql:8.0
    restart: 'always'
    hostname: localhost
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=billablehoursdb
      - MYSQL_PASSWORD=root
      - MYSQL_USER=billablehours_master
    volumes:
      - /data/mysql
    container_name: bha-mysql-docker-container
